package cn.uc.dao;

import cn.uc.model.TComment;

public interface TCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    int insert(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    int insertSelective(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    TComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    int updateByPrimaryKeySelective(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    int updateByPrimaryKey(TComment record);
}