package cn.uc.dao;

import cn.uc.model.TPic;

public interface TPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    int insert(TPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    int insertSelective(TPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    TPic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    int updateByPrimaryKeySelective(TPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pic
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    int updateByPrimaryKey(TPic record);
}