package cn.uc.model;

import java.util.Date;

public class TComment {
    
    private Integer id;

    private TNews tnew;

    private Integer userid;

    private String content;

    private Date createtime;

    private Integer thumbscount;

    private Integer score;

    private Integer status;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

   
    
    public TNews getTnew() {
		return tnew;
	}

	public void setTnew(TNews tnew) {
		this.tnew = tnew;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.content
     *
     * @param content the value for t_comment.content
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.createtime
     *
     * @return the value of t_comment.createtime
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.createtime
     *
     * @param createtime the value for t_comment.createtime
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.thumbscount
     *
     * @return the value of t_comment.thumbscount
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Integer getThumbscount() {
        return thumbscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.thumbscount
     *
     * @param thumbscount the value for t_comment.thumbscount
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setThumbscount(Integer thumbscount) {
        this.thumbscount = thumbscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.score
     *
     * @return the value of t_comment.score
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.score
     *
     * @param score the value for t_comment.score
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.status
     *
     * @return the value of t_comment.status
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.status
     *
     * @param status the value for t_comment.status
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	@Override
	public String toString() {
		return "TComment [id=" + id + ", tnew=" + tnew + ", userid=" + userid + ", content=" + content + ", createtime="
				+ createtime + ", thumbscount=" + thumbscount + ", score=" + score + ", status=" + status + "]";
	}

}