package cn.uc.model;

import java.util.Date;

public class TComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.n_id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Integer nId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.u_id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.content
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.createtime
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.thumbscount
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Integer thumbscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.score
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.status
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.id
     *
     * @return the value of t_comment.id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.id
     *
     * @param id the value for t_comment.id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.n_id
     *
     * @return the value of t_comment.n_id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Integer getnId() {
        return nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.n_id
     *
     * @param nId the value for t_comment.n_id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setnId(Integer nId) {
        this.nId = nId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.u_id
     *
     * @return the value of t_comment.u_id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.u_id
     *
     * @param uId the value for t_comment.u_id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.content
     *
     * @return the value of t_comment.content
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.content
     *
     * @param content the value for t_comment.content
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.createtime
     *
     * @return the value of t_comment.createtime
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.createtime
     *
     * @param createtime the value for t_comment.createtime
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.thumbscount
     *
     * @return the value of t_comment.thumbscount
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Integer getThumbscount() {
        return thumbscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.thumbscount
     *
     * @param thumbscount the value for t_comment.thumbscount
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setThumbscount(Integer thumbscount) {
        this.thumbscount = thumbscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.score
     *
     * @return the value of t_comment.score
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.score
     *
     * @param score the value for t_comment.score
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.status
     *
     * @return the value of t_comment.status
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.status
     *
     * @param status the value for t_comment.status
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public TComment(Integer nId, Integer uId, String content, Date createtime, Integer thumbscount, Integer score,
			Integer status) {
		super();
		this.nId = nId;
		this.uId = uId;
		this.content = content;
		this.createtime = createtime;
		this.thumbscount = thumbscount;
		this.score = score;
		this.status = status;
	}

	public TComment() {
		super();
		// TODO Auto-generated constructor stub
	}

	@Override
	public String toString() {
		return "TComment [id=" + id + ", nId=" + nId + ", uId=" + uId + ", content=" + content + ", createtime="
				+ createtime + ", thumbscount=" + thumbscount + ", score=" + score + ", status=" + status + "]";
	}
    
    
}