package cn.uc.model;

import java.util.Date;

public class TNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.type_id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.title
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.source
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.createtime
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.commcount
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Integer commcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.readcount
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Integer readcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.author
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.sharecount
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Integer sharecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ifhot
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Boolean ifhot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.ifreport
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Boolean ifreport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_news.content
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.id
     *
     * @return the value of t_news.id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.id
     *
     * @param id the value for t_news.id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.type_id
     *
     * @return the value of t_news.type_id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.type_id
     *
     * @param typeId the value for t_news.type_id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.title
     *
     * @return the value of t_news.title
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.title
     *
     * @param title the value for t_news.title
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.source
     *
     * @return the value of t_news.source
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.source
     *
     * @param source the value for t_news.source
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.createtime
     *
     * @return the value of t_news.createtime
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.createtime
     *
     * @param createtime the value for t_news.createtime
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.commcount
     *
     * @return the value of t_news.commcount
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Integer getCommcount() {
        return commcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.commcount
     *
     * @param commcount the value for t_news.commcount
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setCommcount(Integer commcount) {
        this.commcount = commcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.readcount
     *
     * @return the value of t_news.readcount
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Integer getReadcount() {
        return readcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.readcount
     *
     * @param readcount the value for t_news.readcount
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setReadcount(Integer readcount) {
        this.readcount = readcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.author
     *
     * @return the value of t_news.author
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.author
     *
     * @param author the value for t_news.author
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.sharecount
     *
     * @return the value of t_news.sharecount
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Integer getSharecount() {
        return sharecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.sharecount
     *
     * @param sharecount the value for t_news.sharecount
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setSharecount(Integer sharecount) {
        this.sharecount = sharecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ifhot
     *
     * @return the value of t_news.ifhot
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Boolean getIfhot() {
        return ifhot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ifhot
     *
     * @param ifhot the value for t_news.ifhot
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setIfhot(Boolean ifhot) {
        this.ifhot = ifhot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.ifreport
     *
     * @return the value of t_news.ifreport
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Boolean getIfreport() {
        return ifreport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.ifreport
     *
     * @param ifreport the value for t_news.ifreport
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setIfreport(Boolean ifreport) {
        this.ifreport = ifreport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_news.content
     *
     * @return the value of t_news.content
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_news.content
     *
     * @param content the value for t_news.content
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	public TNews() {
		super();
		// TODO Auto-generated constructor stub
	}

	public TNews(Integer typeId, String title, String source, Date createtime, Integer commcount, Integer readcount,
			String author, Integer sharecount, Boolean ifhot, Boolean ifreport, String content) {
		super();
		this.typeId = typeId;
		this.title = title;
		this.source = source;
		this.createtime = createtime;
		this.commcount = commcount;
		this.readcount = readcount;
		this.author = author;
		this.sharecount = sharecount;
		this.ifhot = ifhot;
		this.ifreport = ifreport;
		this.content = content;
	}

	@Override
	public String toString() {
		return "TNews [id=" + id + ", typeId=" + typeId + ", title=" + title + ", source=" + source + ", createtime="
				+ createtime + ", commcount=" + commcount + ", readcount=" + readcount + ", author=" + author
				+ ", sharecount=" + sharecount + ", ifhot=" + ifhot + ", ifreport=" + ifreport + ", content=" + content
				+ "]";
	}
    
    
}