package cn.uc.model;

public class TType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_type.name
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.id
     *
     * @return the value of t_type.id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.id
     *
     * @param id the value for t_type.id
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_type.name
     *
     * @return the value of t_type.name
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_type.name
     *
     * @param name the value for t_type.name
     *
     * @mbggenerated Sun Nov 12 17:27:42 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

	public TType() {
		super();
		// TODO Auto-generated constructor stub
	}

	public TType(String name) {
		super();
		this.name = name;
	}

	@Override
	public String toString() {
		return "TType [id=" + id + ", name=" + name + "]";
	}
    
    
}